//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AccountDetail
{
    public int accNo { get; set; }
    public string accName { get; set; }
    public string accType { get; set; }
    public Nullable<int> accBalance { get; set; }
    public Nullable<int> accBranch { get; set; }

    public virtual BranchInfo BranchInfo { get; set; }
}

public partial class BranchInfo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BranchInfo()
    {
        this.AccountDetails = new HashSet<AccountDetail>();
    }

    public int branchNo { get; set; }
    public string branchName { get; set; }
    public string branchCity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AccountDetail> AccountDetails { get; set; }
}
